# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_start(object):
    def setupUi(self, start):
        start.setObjectName("start")
        start.resize(400, 250)
        self.label_2 = QtWidgets.QLabel(parent=start)
        self.label_2.setGeometry(QtCore.QRect(210, 200, 161, 20))
        self.label_2.setObjectName("label_2")
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=start)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(110, 30, 182, 80))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.label = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        self.label.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.log_name = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget)
        self.log_name.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.log_name.setObjectName("log_name")
        self.verticalLayout.addWidget(self.log_name)
        self.login = QtWidgets.QPushButton(parent=start)
        self.login.setGeometry(QtCore.QRect(165, 150, 75, 24))
        self.login.setObjectName("login")
        self.label_3 = QtWidgets.QLabel(parent=start)
        self.label_3.setGeometry(QtCore.QRect(0, 0, 400, 250))
        self.label_3.setText("")
        self.label_3.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.label_3.setPixmap(QtGui.QPixmap("start.jpg"))
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_3.raise_()
        self.label_2.raise_()
        self.verticalLayoutWidget.raise_()
        self.login.raise_()

        self.retranslateUi(start)
        QtCore.QMetaObject.connectSlotsByName(start)

    def retranslateUi(self, start):
        _translate = QtCore.QCoreApplication.translate
        start.setWindowTitle(_translate("start", "Form"))
        self.label_2.setText(_translate("start", "9.10日下午开发于432实验室"))
        self.label.setText(_translate("start", "在这里输入本次用于对话的用户名"))
        self.login.setText(_translate("start", "开始登录"))
